// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiChatMessage } from "./AiChatMessage";

export type AiChatStructure = { chat_id: bigint, chat_messages: Array<AiChatMessage>, };
