// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiChatMessageRole } from "./AiChatMessageRole";

export type AiChatMessage = { role: AiChatMessageRole, text: string, sent_at: string, move_index: number, };
