// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Board } from "./Board";
import type { BoardState } from "./BoardState";
import type { ChessPiece } from "./ChessPiece";

export type AnalyzerController = { game_id: number, board: Board, current_ply: number, taken_piece_stack: Array<[number, ChessPiece]>, history_stack: Array<BoardState>, };
