// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Board } from "./Board";
import type { LocalChat } from "./LocalChat";
import type { PvObject } from "./PvObject";
import type { UndoInfo } from "./UndoInfo";

export type AnalyzerController = { game_id: number, board: Board, current_ply: number, board_undo: Array<UndoInfo>, last_threat: string | null, last_pv: PvObject | null, chat_history: LocalChat | null, };
