// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Board } from "./Board";

export type AnalyzerController = { game_id: number, board: Board, current_ply: number, };
