// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PieceColor } from "./PieceColor";

export type BoardState = { turn: PieceColor, white_big_castle: boolean, white_small_castle: boolean, black_big_castle: boolean, black_small_castle: boolean, en_passant_target: [number, number] | null, halfmove_clock: number, fullmove_number: number, };
