// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PieceColor } from "./PieceColor";
import type { PieceType } from "./PieceType";

export type BoardUi = { pov: PieceColor, white_taken: Array<[PieceType, PieceColor]>, black_taken: Array<[PieceType, PieceColor]>, };
