// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChessPiece } from "./ChessPiece";
import type { PieceColor } from "./PieceColor";
import type { PieceType } from "./PieceType";

export type BoardUi = { selected_piece: ChessPiece | null, moved_piece: [number, number] | null, pov: PieceColor, white_taken: Array<[PieceType, PieceColor]>, black_taken: Array<[PieceType, PieceColor]>, promtion_pending: [number, number] | null, checkmate_square: [number, number] | null, bar_eval: number, };
