// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PieceColor } from "./PieceColor";
import type { PieceType } from "./PieceType";

export type ChessPiece = { id: number, kind: PieceType, color: PieceColor, position: [number, number], has_moved: boolean, };
