// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EngineCommand = { "SetFen": string } | "GoInfinite" | "Stop" | "Quit" | "Snapshot";
