// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PieceColor } from "./PieceColor";
import type { TerminationBy } from "./TerminationBy";

export type GameController = { player: PieceColor, enemy: PieceColor, game_over: boolean, lost_by: TerminationBy | null, in_check: boolean, };
