// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalMessageRole } from "./LocalMessageRole";

export type LocalMessage = { role: LocalMessageRole, content: string, move_index: number, sent_at: string, };
