// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalMessage } from "./LocalMessage";

export type LocalChat = { chat_id: number, chat_messages: Array<LocalMessage>, };
