// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PieceType } from "./PieceType";

export type MoveInfo = { old_pos: [number, number], new_pos: [number, number], promotion: PieceType | null, is_capture: boolean, };
