// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PieceType } from "./PieceType";

export type MoveKind = { "Normal": { promotion: PieceType | null, } } | { "EnPassant": { captured_at: [number, number], } } | { "Castling": { rook_from: [number, number], rook_to: [number, number], } };
