// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvalResponse } from "./EvalResponse";
import type { PieceType } from "./PieceType";

export type MoveStruct = { move_number: number, san: string, uci: string, promotion: PieceType | null, is_capture: boolean, evaluation: EvalResponse, time_stamp: number, };
