// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PieceMoves = { quiet_moves: Array<[number, number]>, capture_moves: Array<[number, number]>, attacks: Array<[number, number]>, };
