// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvalKind } from "./EvalKind";

export type PvLineData = { moves: string, eval_kind: EvalKind, eval_value: number, };
