// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PvObject = { fen: string, depth: number, lines: { [key in number]?: string }, };
