// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SerializedBoard } from "./SerializedBoard";
import type { UndoInfo } from "./UndoInfo";

export type SerializedAnalyzerController = { game_id: number, serialized_board: SerializedBoard, current_ply: number, board_undo: Array<UndoInfo>, };
