// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SerializedBoardMetaData } from "./SerializedBoardMetaData";

export type SerializedBoard = { fen: string, piece_moves: string, piece_index_mapper: string, meta_data: SerializedBoardMetaData, };
