// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameResult } from "./GameResult";
import type { TerminationBy } from "./TerminationBy";

export type SerializedBoardMetaData = { starting_position: string, date: string, move_list: string, termination: TerminationBy, result: GameResult, white_player_elo: number, black_player_elo: number, white_player_name: string, black_player_name: string, opening: string | null, event: string | null, site: string | null, round: string | null, time_control: string | null, end_time: string | null, link: string | null, eco: string | null, };
