// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameControllerMode } from "./GameControllerMode";
import type { GameControllerState } from "./GameControllerState";
import type { GameResult } from "./GameResult";
import type { PieceColor } from "./PieceColor";
import type { SerializedBoard } from "./SerializedBoard";
import type { TerminationReason } from "./TerminationReason";

export type SerializedGameController = { player: PieceColor, mode: GameControllerMode, player_card: string, engine_card: string, board: SerializedBoard, player_clock: number, engine_clock: number, state: GameControllerState, termination_reason: TerminationReason | null, result: GameResult | null, elo_gain: number | null, can_be_abandoned: boolean, };
