// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoardState } from "./BoardState";
import type { ChessPiece } from "./ChessPiece";
import type { MoveKind } from "./MoveKind";

export type UndoInfo = { from: [number, number], to: [number, number], captured: ChessPiece | null, prev_state: BoardState, kind: MoveKind, };
