// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PieceType } from "./PieceType";

export type UpdateType = "EngineMove" | { "Playermove": { from: [number, number], to: [number, number], promotion: PieceType | null, } };
